import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// ─── Pass 1: Bundle the tile worker as a self-contained IIFE ─────────

const workerEntryPoint = "src/canvas/tiles/worker/tileWorker.ts";
const workerOutfile = "build/tileWorker.iife.js";

async function buildWorker() {
  await esbuild.build({
    entryPoints: [workerEntryPoint],
    bundle: true,
    // No externals — everything is inlined into the worker
    format: "iife",
    target: "es2018",
    logLevel: "warning",
    sourcemap: false,
    treeShaking: true,
    outfile: workerOutfile,
    minify: prod,
    loader: {
      ".ts": "ts",
      ".tsx": "tsx",
    },
  });
  return fs.readFileSync(workerOutfile, "utf-8");
}

// ─── Plugin: Inject worker code as a string literal ──────────────────

function tileWorkerPlugin(workerCode) {
  return {
    name: "tile-worker-inline",
    setup(build) {
      // Virtual module that resolves "tile-worker-code" import
      build.onResolve({ filter: /^tile-worker-code$/ }, () => ({
        path: "tile-worker-code",
        namespace: "tile-worker-inline",
      }));

      build.onLoad(
        { filter: /^tile-worker-code$/, namespace: "tile-worker-inline" },
        () => ({
          contents: `export default ${JSON.stringify(workerCode)};`,
          loader: "js",
        }),
      );
    },
  };
}

// ─── Pass 2: Main bundle with worker code injected ───────────────────

// Ensure build output directory exists
fs.mkdirSync("build", { recursive: true });

const workerCode = await buildWorker();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  loader: {
    ".ts": "ts",
    ".tsx": "tsx",
  },
  plugins: [tileWorkerPlugin(workerCode)],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log("Watching for changes...");
}
